routes/web.php
<?php

use App\Http\Controllers\CourseController;
use App\Http\Controllers\LoginController;
use App\Http\Controllers\RegistrationController;
use Illuminate\Support\Facades\Route;


Route::resource('courses', CourseController::class)->except([
    'show',
]);

Route::get('courses/api', [CourseController::class, 'api'])->name('courses.api');
Route::get('/', function(){
    return view('auth.login');
});
Route::get('login_show',[LoginController::class, 'login_show'])->name('login_show');
Route::post('login',[LoginController::class, 'login'])->name('login');
Route::get('registration_show',[LoginController::class,'registration_show'])->name('registration_show');
Route::post('registration',[LoginController::class,'registration'])->name('registration');
//
//Route::get('logout',[LoginController::class,'logout'])->name('logout');

app/Models/Course.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Course extends Model
{
    use HasFactory;
    public $timestamps =false;

    protected $fillable = ['name','detail','price'];



}

app/Models/User.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Notifications\Notifiable;


class User extends Model
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'username', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */

    /**
     * Add a mutator to ensure hashed passwords
     */
    public function setPasswordAttribute($password)
    {
        $this->attributes['password'] = bcrypt($password);
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/CourseController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Course\DestroyRequest;
use App\Http\Requests\Course\StoreRequest;
use App\Http\Requests\Course\UpdateRequest;

use App\Http\Requests\Course\RegistrationRequest;
use App\Models\Course;
use Illuminate\Http\Request;
use Yajra\DataTables\DataTables;


class CourseController extends Controller
{



    public function index()
    {
        return view('course.index');
    }

    public function api()
    {
        return DataTables::of(Course::query())
            ->addColumn('edit', function ($object) {
                return route('courses.edit', $object);
            })
            ->addColumn('destroy', function ($object) {
                return route('courses.destroy', $object);
            })
            ->make(true);
    }

    public function create()
    {
        return view('course.create');
    }

    public function store(StoreRequest $request)
    {
//         $object = new Course();
//         $object->save();

        Course::create($request->validated());

        return redirect()->route('courses.index');
    }

    public function edit(Course $course)
    {
        return view('course.edit', [
            'each' => $course,
        ]);
    }

    public function update(Request $request, Course $course)
    {
         Course::query()->where('id', $course->id)->update(
             $request->except([
                 '_token',
                 '_method',
             ])
         );
         $course->update(
             $request->except([
                 '_token',
                 '_method',
             ])
         );
//
//        $course->fill($request->validated());
//        $course->save();

        return redirect()->route('courses.index');
    }

    public function destroy(DestroyRequest $request, $course)
    {
        // $course->delete();
        Course::destroy($course);
        // Course::where('id', $course->id)->delete();
        $arr = [];
        $arr['status'] = true;
        $arr['message'] = '';
        return response($arr, 200);
    }

}

app/Http/Controllers/LoginController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\Course\RegistrationRequest;
use App\Models\Course;
use App\Models\User;
use Illuminate\Http\Request;

class LoginController extends Controller
{
    //login
    public function login_show(){
        return view('course.login');
    }
    public function login(){
        dd(12345);
        return view('course.login');
    }
    public function registration_show(){
        return view('course.registration');
    }
    public function registration(Request $request){
        $object= new User();
        $object->fill($request->all());
        $object->save();
        return view('course.login');
    }
}
//mở cái view đó ra

resources/views/course/create.blade.php
{{--<form action="{{ route('courses.store') }}" method="post">--}}
{{--    @csrf--}}
{{--    Name--}}
{{--    <input type="text" name="name" value="{{ old('name') }}">--}}

{{--    @if($errors->has('name'))--}}
{{--        <span class="error">--}}
{{--            {{ $errors->first('name') }}--}}
{{--        </span>--}}
{{--    @endif--}}
{{--    <br>--}}
{{--    <button>Create</button>--}}

@extends('layout.master')
@push('css')
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.11.5/b-2.2.2/b-colvis-2.2.2/b-html5-2.2.2/b-print-2.2.2/date-1.1.2/fc-4.0.2/fh-3.2.2/r-2.2.9/rg-1.1.4/sc-2.0.5/sb-1.3.2/sl-1.3.4/datatables.min.css"/>
@endpush
@section('content')
    <div class='card'>
            <form action="{{ route('courses.store') }}" method="post" style="padding: 30px; text-align: center">
                @csrf
                <label>Name:</label>
                <input type="text" name="name" style="margin-left: 50px; margin-bottom: 10px">
                <br>
                <label>Detail:</label>
                <input type="text" name="detail"  style="margin-left: 50px; margin-bottom: 10px">
                <br>
                <label>Price:</label>
                <input type="number" name="price" style="margin-left: 56px; margin-bottom: 10px">
                <br>
                <button class="btn btn-primary">Create</button>
            </form>
    </div>
@endsection

resources/views/course/edit.blade.php
{{--<form action="{{ route('courses.update', $each) }}" method="post">--}}
{{--    @csrf--}}
{{--    @method('PUT')--}}
{{--    Name--}}
{{--    <input type="text" name="name" value="{{ $each->name }}">--}}
{{--    @if($errors->has('name'))--}}
{{--        <span class="error">--}}
{{--            {{ $errors->first('name') }}--}}
{{--        </span>--}}
{{--    @endif--}}
{{--    <br>--}}
{{--    <button>Update</button>--}}
{{--</form>--}}
@extends('layout.master')
@push('css')
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.11.5/b-2.2.2/b-colvis-2.2.2/b-html5-2.2.2/b-print-2.2.2/date-1.1.2/fc-4.0.2/fh-3.2.2/r-2.2.9/rg-1.1.4/sc-2.0.5/sb-1.3.2/sl-1.3.4/datatables.min.css"/>
@endpush
@section('content')
    <div class='card'>
        @if ($errors->any())
            <div class="card-header">
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif
        <form action="{{route('courses.update', $each)}}" method="post" style="padding: 30px; text-align: center">
            @csrf
            @method('PUT')
            <label>Name:</label>
            <input type="text" name="name" value="{{$each->name}}" style="margin-left: 50px; margin-bottom: 10px">
            <br>
            <label>Detail:</label>
            <input type="text" name="detail" value="{{$each->detail}}" style="margin-left: 50px; margin-bottom: 10px">
            <br>
            <label>Price:</label>
            <input type="number" name="price" value="{{$each->price}}" style="margin-left: 56px; margin-bottom: 10px">
            <br>
            <button class="btn btn-primary">Update</button>
        </form>
    </div>
@endsection

resources/views/course/index.blade.php
@extends('layout.master')
@push('css')
    <link rel="stylesheet" type="text/css"
          href="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.11.5/b-2.2.2/b-colvis-2.2.2/b-html5-2.2.2/b-print-2.2.2/date-1.1.2/fc-4.0.2/fh-3.2.2/r-2.2.9/rg-1.1.4/sc-2.0.5/sb-1.3.2/sl-1.3.4/datatables.min.css"/>
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
@endpush
@section('content')
    <div class='card'>
        @if ($errors->any())
            <div class="card-header">
                <div class="alert alert-danger">
                    <ul>
                        @foreach ($errors->all() as $error)
                            <li>{{ $error }}</li>
                        @endforeach
                    </ul>
                </div>
            </div>
        @endif
        <div class='card-body'>
            <a class="btn btn-success" href="{{ route('courses.create') }}" style="margin-bottom: 10px">
                Add
            </a>
            <table class="table table-striped" id="table-index">
                <thead>
                <tr>
                    <th>#</th>
                    <th>Name</th>
                    <th>Detail</th>
                    <th>Price</th>
                    <th>Edit</th>
                    <th>Delete</th>
                </tr>
                </thead>
            </table>
        </div>
    </div>
@endsection
@push('js')
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/vfs_fonts.js"></script>
    <script type="text/javascript" src="https://cdn.datatables.net/v/dt/jszip-2.5.0/dt-1.11.5/b-2.2.2/b-colvis-2.2.2/b-html5-2.2.2/b-print-2.2.2/date-1.1.2/fc-4.0.2/fh-3.2.2/r-2.2.9/rg-1.1.4/sc-2.0.5/sb-1.3.2/sl-1.3.4/datatables.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
        <script>
            $(function() {
            var buttonCommon = {
            exportOptions: {
            columns: ':visible :not(.not-export)'
        }
        };
            let table = $('#table-index').DataTable({
            dom: 'Blrtip',
            select: true,
            buttons: [
            $.extend( true, {}, buttonCommon, {
            extend: 'copyHtml5'
        } ),
            $.extend( true, {}, buttonCommon, {
            extend: 'excelHtml5'
        } ),
            $.extend( true, {}, buttonCommon, {
            extend: 'pdfHtml5'
        } ),
            $.extend( true, {}, buttonCommon, {
            extend: 'print'
        } ),
            'colvis'
            ],
            processing: true,
            serverSide: true,
            ajax: '{!! route('courses.api') !!}',
            columnDefs: [
            {className: "not-export", "targets": [ 3 ] }
            ],
            columns: [
                { data: 'id', name: 'id' },
                { data: 'name', name: 'name' },
                { data: 'detail', name: 'detail' },
                { data: 'price', name: 'price' },

        {
            data: 'edit',
            targets: 4,
            orderable: false,
            searchable: false,
            render: function ( data, type, row, meta ) {
            return `<a class="btn btn-primary" href="${data}">
             Edit
            </a>`;
        }
        },
        {
            data: 'destroy',
            targets: 5,
            orderable: false,
            searchable: false,
            render: function ( data, type, row, meta ) {
            return `<form action="${data}" method="post">
            @csrf
            @method('DELETE')
            <button type='button' class="btn-delete btn btn-danger">Delete</button>
        </form>`;
        }
        },
            ]
        });
            $(document).on('click','.btn-delete',function(){
            let form = $(this).parents('form');
            $.ajax({
            url: form.attr('action'),
            type: 'POST',
            dataType: 'json',
            data: form.serialize(),
            success: function() {
            console.log("success");
            table.draw();
        },
            error: function() {
            console.log("error");
        }
        });
        });
        });

    </script>

@endpush

resources/views/course/login.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Login LaSStore</title>
    <link rel="stylesheet" href="{{ URL::asset('css/style-login.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
<div class="header">
    <h2>Login</h2>
</div>
<form method="post" action="{{route('login')}}}">
    @csrf
    <div class="input-group">
        aaaaaaaaaaaaaaaaaaaa ta
        <label>Username</label>
        <input type="text" name="username"   required>
    </div>

    <div class="input-group">
        <label>Password</label>
        <input type="password" name="password" required>
    </div>

    <div class="input-group">
        <button type="submit" class="btn">Login</button>
    </div>
    <p>
        Not yet a account? <a href="{{route('registration_show')}}">Sign up</a>
    </p>
</form>
</body>
</html>

resources/views/course/registration.blade.php
<!DOCTYPE html>
<html>
<head>
    <title>Login</title>
    <link rel="stylesheet" href="{{ URL::asset('css/style-login.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
</head>
<body>
<div class="header">
    <h2>Register</h2>
</div>
<form action="{{route('registration')}}" method="post" >
    {{ csrf_field() }}
    <div class="input-group">
        <label>Email</label>
        <input type="text" name="email" required>
    </div>

    <div class="input-group">
        <label>Username</label>
        <input type="text" name="username" required>
    </div>

    <div class="input-group">
        <label>Password</label>
        <input type="password" name="password" required>
    </div>

    <div class="input-group">
        <label>Confirm Password</label>
        <input type="password" name="confirm_password"required>
    </div>

    <div class="input-group">
        <button type="submit" class="btn" >Register</button>
    </div>
</form>
</body>
</html>
@if(session('success'))
    {{session('success')}}
@endif

resources/views/layout/footer.blade.php
<footer class="footer">
    <div class="container-fluid">
        <div class="row">
            <div class="col-md-6">
                2022 @ Nhóm 9 Kiến Trúc Phần Mềm
            </div>
            <div class="col-md-6">
                <div class="text-md-right footer-links d-none d-md-block">
                    <a href="#">About</a>
                    <a href="#">Support</a>
                    <a href="#">Contact Us</a>s
                </div>
            </div>
        </div>
    </div>
</footer>

resources/views/layout/header.blade.php
<div class="navbar-custom">
    <ul class="list-unstyled topbar-right-menu float-right mb-0">
        <li class="dropdown notification-list d-lg-none">
            <a class="nav-link dropdown-toggle arrow-none" data-toggle="dropdown" href="#" role="button"
               aria-haspopup="false" aria-expanded="false">
                <i class="dripicons-search noti-icon"></i>
            </a>
            <div class="dropdown-menu dropdown-menu-animated dropdown-lg p-0">
                <form class="p-3">
                    <input type="text" class="form-control" placeholder="Search ..."
                           aria-label="Recipient's username">
                </form>
            </div>
        </li>


        <li class="dropdown notification-list">
            <a class="nav-link dropdown-toggle nav-user arrow-none mr-0" data-toggle="dropdown" href="#"
               role="button" aria-haspopup="false"
               aria-expanded="false">
                <span class="account-user-avatar">
                    <img src="{{asset('image/pq.jpg')}}" alt="user-image"
                         class="rounded-circle">
                </span>
                <span>
                    <span class="account-user-name">Huynh Phuong</span>
                    <span class="account-position">Admin</span>
                </span>
            </a>
            <div class="dropdown-menu dropdown-menu-right dropdown-menu-animated topbar-dropdown-menu profile-dropdown">
                <!-- item-->
                <div class=" dropdown-header noti-title">
                    <h6 class="text-overflow m-0">Welcome !</h6>
                </div>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="mdi mdi-account-circle mr-1"></i>
                    <span>My Account</span>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="mdi mdi-account-edit mr-1"></i>
                    <span>Settings</span>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="mdi mdi-lifebuoy mr-1"></i>
                    <span>Support</span>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="mdi mdi-lock-outline mr-1"></i>
                    <span>Lock Screen</span>
                </a>

                <!-- item-->
                <a href="javascript:void(0);" class="dropdown-item notify-item">
                    <i class="mdi mdi-logout mr-1"></i>
                    <span>Logout</span>
                </a>

            </div>
        </li>

    </ul>
    <button class="button-menu-mobile open-left disable-btn">
        <i class="mdi mdi-menu"></i>
    </button>

</div>

resources/views/layout/master.blade.php
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8"/>
    <title>Admin - Management</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta content="A fully featured admin theme which can be used to build CRM, CMS, etc." name="description"/>
    <meta content="Coderthemes" name="author"/>
    <!-- App favicon -->


    <!-- App css -->
    <link href="{{ asset('css/icons.min.css') }}" rel="stylesheet" type="text/css"/>
    <link href="{{ asset('css/app-creative.min.css') }}" rel="stylesheet" type="text/css"/>
    @stack('css')
</head>

<body data-layout-config='{"leftSideBarTheme":"dark","layoutBoxed":false, "leftSidebarCondensed":false, "leftSidebarScrollable":false,"darkMode":false, "showRightSidebarOnStart": true}'>
@include('layout.sidebar')
<div class="wrapper">
    @include('layout.header')
    <div class="content-page">
        <div class="content">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-12">
                        <div class="page-title-box">
                            <h1 class="page-title">Product Management </h1>
                        </div>
                    </div>
                </div>
                <div class="row">
                    <div class="col-12">
                        @yield('content')
                    </div>
                </div>
            </div>
        </div>
        @include('layout.footer')
    </div>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.6.0/jquery.min.js"></script>
<script src="{{ asset('js/vendor.min.js') }}"></script>
<script src="{{ asset('js/app.min.js') }}"></script>
@stack('js')
</body>
</html>

resources/views/layout/sidebar.blade.php
<!-- ========== Left Sidebar Start ========== -->
<div class="left-side-menu">


        <!--- Sidemenu -->
        <ul class="metismenu side-nav">

            <li class="side-nav-title side-nav-item">Menu</li>

            <li class="side-nav-item">
                <a href="javascript: void(0);" class="side-nav-link">
                    <i class="uil-home-alt"></i>
                    <span class="badge badge-success float-right">5</span>
                    <span> Dashboards </span>
                </a>
                <ul class="side-nav-second-level" aria-expanded="false">
                    <li>
                        <a href="#">Employee management</a>
                    </li>
                    <li>
                        <a href="#">Product Management</a>
                    </li>
                    <li>
                        <a href="#">Order management</a>
                    </li>
                    <li>
                        <a href="#">Chart</a>
                    </li>
                    <li>
                        <a href="#">Statistical</a>
                    </li>
                </ul>
            </li>
        <div class="clearfix"></div>

        </ul>
    <!-- Sidebar -left -->

</div>